theme: jekyll-theme-slate

title: TAIL - Technology and Artificial Intelligence League 
description:  A study and research community in technology and artificial intelligence. 
url: http://tailufpb.github.io
#description: Hello, I'm Manuel, read more about me below.
#author: 

email: tail.ufpb@gmail.com
github-url: tailufpb
#linkedin: www.linkedin.com/in/manuel-ferreira-junior

#logo: 'assets/img/ava.png'
# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

social-network-links:
  email: "tail.ufpb@gmail.com"
  github: tailufpb
  twitter: '@'
  instagram: '@tailufpb'
  rss: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
